### ISSUE TITLE
Can you help me to follow your work?

### ISSUE THREAD

**Issue by baoy-nlp** [ZiqiaoZhang/FraSICL#1]
Hi, Ziqiao

Thanks for sharing your codebase!

I am interested in your excellent work on "Molecular Property Prediction by Semantic-invariant Contrastive Learning."
I want to follow it, but its current version misses a training framework package and pre-training datasets.

Could you update the repo and upload runnable scripts, pre-training dataset (and pre-trained model checkpoints, if possible)?

Thanks so much!

**Comment by ZiqiaoZhang** [comment]
Hi,

Thank you for your interest.

I am planning to update the repository this weekend.

**Comment by ZiqiaoZhang** [comment]
Dataset and checkpoints have been uploaded.

**Comment by ZiqiaoZhang** [comment]
Training Package and Scripts have been uploaded.
