### ISSUE TITLE
 No module named 'FragComponents'

### ISSUE THREAD

**Issue by pearl-rabbit** [ZiqiaoZhang/FraSICL#2]
File './FraSICL/TrainingFramework/Featurizer.py", line 9, in <module>
    from FragComponents.Utils import *
ModuleNotFoundError: No module named 'FragComponents'

**Comment by ZiqiaoZhang** [comment]
FragComponents/Utils.py is uploaded. Please try it again.

**Comment by pearl-rabbit** [comment]
OK, thanks.
